# Generated by Django 5.2.16 on 2026-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0004_alter_userwechatprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingWechatBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce_digest", models.CharField(max_length=64, unique=True)),
                ("openid", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "待绑定微信凭据",
                "verbose_name_plural": "待绑定微信凭据",
            },
        ),
    ]
